### ISSUE TITLE
V3.0.9 Staging Snag List

### ISSUE THREAD

**Issue by paulgosnell** [fitlink-app/fitlink-monorepo#494]
### High Priority
- [x] CRITICAL 1: Update leagues with new bfit_distributed_today #523 
- [x] CRITICAL 2: 7-Day BFIT Panel > Check/implement new response structure #520 
- [x] CRITICAL 3: Finish disabling to "claim" button to avoid multiple claims #528 
- [x] Sport-type label position needs fixing, see #518
- [x] Update single activity screen so the bar is vertically centered giving more room for map, see #499 
- [x] Hook up token sale page to buy button in wallet screen, see #498 
- [x] Google Fit OAuth Verification Request, see #504
- [x] Background crash: This issue has 43 crash events affecting 10 users, see crashlytics [here](https://console.firebase.google.com/u/0/project/bfit-production/crashlytics/app/ios:com.bfitcoin/issues/89cef18f608e0b96a2760ddfc7daef10?time=last-seven-days&sessionEventKey=0907de78c55145a5abaea2e86632fe01_1782429022492826948)
- [x] The Leaderboard title in leagues is too big. Please reduce as per design
- [x] Goal rings to show number value in centre of ring on tap - Android done but can't test iOS 
- [x] Disable and show popup on claim button when BFIT 0, see #483 
- [x] Leagues > include sport-type in panels #467 - Android done but can't test iOS 
- [x] Intercom updates #447
- [x] Calorie panel on leagues screen to be replaced with BFIT panel
- [x] When tapping BFIT panel on all screens it should take you to wallet screen
- [x] Whenever a user taps a BFIT value label it should show $ value (as it does in rewards)
