### ISSUE TITLE
API Snagging List

### ISSUE THREAD

**Issue by paulgosnell** [fitlink-app/fitlink-monorepo#496]
### High priority

- [ ] Sort leagues by BFIT, see #503 
- [ ] Total BFIT value wrong on wallet screen, see #500 
- [ ] 7-day summary data on BFIT panel not as expected, see #452 
- [ ] Login > Bundle ID switcher for Apple, Google, Strava, Fitbit services, see #427 
- [ ] I was able to over-cliam BFIT in steps league, see #497 
- [ ] Claim button allowing multiple claims, see #501
- [ ] Add `weightTraining` as a new sports type, see #450 
- [ ] Strava activity data not syncing and lots of errors in [web-server-errors](https://fitlinkworkspace.slack.com/archives/C02HE3C0WFP/p1677294560791969), see #456 

### Low priority

- [ ] Wallet > update `walletTransaction` text/label, see #428 
- [ ] Update `/me` so we can get previous `points_week` in the same way as 7-day summary data works, see #327
